

export default function WasteFacts(){
    return(
        <div className="WasteFactsComponent">
            <h2>Putting Waste into Perspective</h2>	
            <p><a href="https://www.janssenpmp.com/sustainability/articles/up-to-40-percent-of-food-is-wasted-before-it-reaches-the-market#:~:text=According%20to%20the%20Food%20and,not%20reach%20the%20end%20consumer.">40% of food</a> is wasted each year in the United States. But what does that look like? Where does that all go—or not go? That is nearly <a href="https://www.rts.com/resources/guides/food-waste-america/">60 million tons</a>—120 billion pounds—each year, worth <a href="https://www.forbes.com/sites/chloesorvino/2022/07/14/food-waste-costs-us-taxpayers-billions-of-dollars-a-year/?sh=51a4114542ea">$400 billion</a>.<sup className="superscript">1</sup> <a href="https://www.ers.usda.gov/data-products/ag-and-food-statistics-charting-the-essentials/food-security-and-nutrition-assistance/#:~:text=The%20prevalence%20of%20food%20insecurity,of%20a%20lack%20of%20resources.">12.8% of households</a><sup className="superscript">2</sup> in the US—including <a href="https://www.feedingamerica.org/hunger-in-america/child-hunger-facts#:~:text=More%20than%2013%20million%20children,will%20get%20their%20next%20meal.">13 million children</a>—are food insecure while 40% of the food resources are wasted. Hunger is not unsolvable; it is not a problem of resources but of structure.</p>
            <p>What about that $400 billion? Wasted food costs taxpayers <a href="https://www.forbes.com/sites/chloesorvino/2022/07/14/food-waste-costs-us-taxpayers-billions-of-dollars-a-year/?sh=51a4114542ea">billions</a> each year, as corporations receive a tax-deduction for the 'cost of shrinkage' or loss of profits.<sup className="superscript">3</sup> Produce that winds up in the landfill cannot break down properly due to a lack of oxygen and produces methane, which has a greenhouse effect <a href="https://energy.ec.europa.eu/topics/oil-gas-and-coal/methane-emissions_en#:~:text=In%20fact%2C%20methane's%20ability%20to,on%20a%2020%2Dyear%20timescale.">~80x more potent than that of CO2</a>. Globally, food waste accounts for <a href="https://www.forbes.com/sites/chloesorvino/2022/07/14/food-waste-costs-us-taxpayers-billions-of-dollars-a-year/?sh=51a4114542ea">8% of all greenhouse gas emisions</a>.</p>
            <p>Moreover, the farming practices used to maintain the steady flow of food through the market has adverse effects on soil health and nutrient density in food. Monocropping depletes soil of nutrients and affects <a href="https://www.nhm.ac.uk/discover/soil-degradation.html#:~:text=Soil%20can%20lose%20certain%20physical,such%20as%20poor%20land%20management.">the biodiversity of microbiota</a> that play a crucial symbiotic role in fighting off pests and promoting plant growth and health. Disrupting the topsoil also diminishes the amount of fixed carbon it can store <a href="https://www.nhm.ac.uk/discover/soil-degradation.html#:~:text=Soil%20can%20lose%20certain%20physical,such%20as%20poor%20land%20management.">by 50-75%</a>, thereby contributing to and exacerbating the effects of climate change. In order to combat weeds and pests, farmers resort to toxic pesticides and herbicides that further damage the soil microbiome, creating a negative feedback loop.</p>
            <p>As of 2019, estimates say that the food industry generates <a href="https://www.plasticsoupfoundation.org/en/2021/12/food-production-causes-plastic-pollution/#:~:text=FAO%20estimates%20that%20in%202019,biggest%20user%2C%20up%20to%202030.">12.5 million tons of single use plastic</a> annually. Assuming an even 40% of this plastic goes to the landfill, that is 5 million tons of unnecessary plastic each year. Plastic is not 'broken down' and recycled like organic molecules; instead, it breaks apart into smaller microplastics and nanoplastics, which get into our water and food. These microplastics have been detected in blood samples in almost <a href="https://www.theguardian.com/environment/2022/mar/24/microplastics-found-in-human-blood-for-first-time#:~:text=Microplastic%20pollution%20has%20been%20detected,and%20may%20lodge%20in%20organs.">80% of people tested</a> and in <a href="https://www.theguardian.com/environment/2024/feb/27/microplastics-found-every-human-placenta-tested-study-health-impact#:~:text=The%20research%2C%20published%20in%20the,common%20plastics%20detected%2C%20after%20polyethylene.">every human placenta tested</a>. While research on <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10151227/">the health effects of exposure to microplastics on humans</a> is still limited, research shows that high <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9205308/">high concentrations of microplastics are harmful to smaller life forms</a>.</p>
            <div className="footnotes">
                <h3>Footnotes</h3>
                <p><sup className="superscript">1</sup> The average grocer in the U.S. is estimated to waste between <a href="https://www.forbes.com/sites/chloesorvino/2022/07/14/food-waste-costs-us-taxpayers-billions-of-dollars-a-year/?sh=51a4114542ea">$5,000 and $10,000</a> of food each week.</p>
                <p><sup className="superscript">2</sup> The 2022 <a href="https://www.census.gov/library/publications/2023/demo/p60-279.html#:~:text=Highlights,and%20Table%20A%2D1).">average annual household income was $74580</a>. That is ~ $6,215 per month; in other words, the average grocer wastes more than the average household monthly income nearly every single week of the year.</p>
                <p><sup className="superscript">3</sup> Current tax law actually creates "<a href="https://www.forbes.com/sites/chloesorvino/2022/07/14/food-waste-costs-us-taxpayers-billions-of-dollars-a-year/?sh=51a4114542ea">a powerful disincentive</a>" to improving or eradicating this problem.</p>
            </div>
        </div>
    )
}